# Generated by Django 4.1.2 on 2022-10-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citi', models.CharField(max_length=150)),
                ('country', models.CharField(default='Ukraine', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Сlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('p_email', models.EmailField(max_length=254)),
                ('cities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('clients', models.ManyToManyField(to='catalog.сlient')),
            ],
        ),
    ]
