# Generated by Django 4.1.2 on 2022-10-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сlient',
            new_name='Client',
        ),
    ]
