# Generated by Django 4.1.2 on 2022-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_logmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='request_get',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='request_post',
            field=models.JSONField(default={}),
        ),
    ]
