# Generated by Django 4.1.2 on 2022-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_logmodel_request_get_logmodel_request_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='request_get',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='request_post',
            field=models.JSONField(default=dict),
        ),
    ]
